# .circleci/config.yml
version: 2.1
workflows:
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  release:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: 
        name: build
        no_output_timeout: 60m
        command: curl -sL https://git.io/goreleaser | bash
